print('----------------------------------------------------------tw:@tek_elo')
print('numpy kullanımı\n')
print('---------------------------------------------------------------------')
print()
import numpy as np
a=np.array([1,5,10])
b=np.array([[1,7,20],[5,8,9]])
print(b)
print('-------dizi boyutunu öğrenmek-----------------')
print(a.ndim)
print(b.ndim)
print('-------iki boyutlu dizi boyutunu öğrenmek-----------------')
print(b.shape)
print(a.shape)
print('-------veri tipini öğrenmek-----------------')
print(a.dtype)
print(b.dtype)
c=np.array([1.5,4.3,8])
print(c.dtype)
