import json # gelen json verilerini yapılandırmak için
data="""
    {
        "firstName":"Sadık",
        "lastName":"Turan",
        "hobbies":["spor","sinema"],
        "age":37,
        "children":[
            {
                "firstName":"Çınar",
                "age":4         
            },
            {
                "firstName":"Ahmet",
                "age":2         
            }
    
        ]
    }
"""
data=json.loads(data)
print(data)
print(type(data))
print(data["firstName"])
print(data["hobbies"])
print(data["hobbies"][0])
print(data["children"])
print(data["children"][0])
print(data["children"][0]["age"])
