print('----------------------------------------------------------tw:@tek_elo')
print('imdb veritabanı\n')
print('---------------------------------------------------------------------')
print()
import pandas as pd
df = pd.read_csv('imdb_top_1000.csv')
#df.head(5)
print(df.head(5))
print()
#df.tail(5)
print(df.tail(5))
print('-------------------------')
print(df.shape)
print('-------------------------')
print(len(df))
print('-------------------------')
print(df.columns)
print('-------------------------')
print(df.dtypes)
print('-------------------------')
print(df.isnull)
print('-------------------------')
print(df['Series_Title'])
print('-------------------------')
print(df['Series_Title'][:5])
print('-------------------------')
df2 = df[['Series_Title', 'Released_Year']]
print(df2)
print('-------------------------')
print(df.sort_values('Released_Year'))
print('-------------------------')
print(df['Released_Year'].value_counts())